# Generated by Django 4.0.3 on 2022-03-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
