# Generated by Django 4.0.4 on 2022-04-15 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_customer2_order_date_created_order_date_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer2',
        ),
        migrations.AlterField(
            model_name='order',
            name='who_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
    ]
