# Generated by Django 4.0.4 on 2022-04-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_order_customer2_alter_order_who_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
