# Generated by Django 4.0.4 on 2022-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CARD', 'CARD')], default='CASH', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
