# Generated by Django 4.0.4 on 2022-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_date_created_alter_order_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_total_when_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
